trigger:
- main

pool:
  vmImage: 'my_laptop'

steps:

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '24.x'

- script: |
    node --version
    npm --version
  displayName: 'Check Node.js and npm'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'Run unit tests'