trigger:
- main

pool:
  name: aws-ec2-pool

steps:

- script: |
    node --version
    npm --version
  displayName: 'Check Node.js and npm'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'Run unit tests'

- task: Npm@1
  displayName: 'Publish package to Azure Artifacts'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: 'new_npm/npm-feed'
- script: |
    docker build -t my-node-ci-cd:$(Build.BuildId) .
  displayName: 'Build Docker image'

